package com.example.greeting;

/**
 * Represents the response sent back to the frontend.
 * Contains the greeting message generated by the backend.
 */
public class GreetingResponse {

    private String message;

    // Default constructor (required for JSON serialization)
    public GreetingResponse() {}

    public GreetingResponse(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}
